import { MedicineItem, MedicalRecord, DoctorProfile } from './types';

export const MEDICINES_DATA: MedicineItem[] = [
  {
    id: 'med-1',
    name: 'Paracetamol',
    gujaratiName: 'પેરાસિટામોલ',
    hindiName: 'पैरासिटामोल',
    status: 'valid',
    expiryDate: '2026-11',
    expiryText: {
      EN: 'Expires: 2026',
      GU: 'સમાપ્તિ: 2026',
      HI: 'समाप्ति: 2026',
    },
    dosage: '500 mg • 1 tablet after meals (SOS fever/pain)',
    batch: 'B#PC-8842',
    notes: 'Safe for fever and mild body ache. Do not exceed 4000mg/day.',
  },
  {
    id: 'med-2',
    name: 'Amoxicillin',
    gujaratiName: 'એમોક્સિસિલિન',
    hindiName: 'एमोक्सिसिलिन',
    status: 'expired',
    expiryDate: '2024-08',
    expiryText: {
      EN: 'Expired / સમય પૂરો થયો છે!',
      GU: 'Expired / સમય પૂરો થયો છે!',
      HI: 'Expired / अवधि समाप्त हो चुकी है!',
    },
    dosage: '250 mg Capsule • Antibiotic',
    batch: 'B#AMX-1092',
    notes: 'DO NOT CONSUME. Degraded antibiotic may cause kidney stress or lack efficacy.',
  },
  {
    id: 'med-3',
    name: 'Metformin HCl',
    gujaratiName: 'મેટફોર્મિન',
    hindiName: 'मेटफॉर्मिन',
    status: 'valid',
    expiryDate: '2027-04',
    expiryText: {
      EN: 'Expires: 2027',
      GU: 'સમાપ્તિ: 2027',
      HI: 'समाप्ति: 2027',
    },
    dosage: '500 mg • Daily before breakfast',
    batch: 'B#MET-504',
    notes: 'Blood sugar regulation. Regularly monitor HbA1c.',
  },
];

export const RECORDS_DATA: MedicalRecord[] = [
  {
    id: 'rec-1',
    title: 'Complete Blood Count (CBC) Panel',
    gujaratiTitle: 'સંપૂર્ણ રક્ત ગણતરી (CBC) રિપોર્ટ',
    hindiTitle: 'कम्पलीट ब्लड काउंट (CBC) रिपोर्ट',
    date: '14 Sep 2026',
    hospital: 'Civil Hospital Ahmedabad, Asarwa',
    doctor: 'Dr. A. Sharma (MD)',
    badge: 'Lab Report',
    type: 'lab_report',
    geminiSummary: {
      EN: [
        'Hemoglobin is optimal at 14.2 g/dL (Normal Range 13.0 - 17.0).',
        'Platelet count normal (2.45 Lakhs/mcL).',
        'No active bacterial inflammation indicated in WBC count.',
        'Recommendation: Continue hydration and balanced iron-rich diet.'
      ],
      GU: [
        'હિમોગ્લોબિન સામાન્ય સ્તરે 14.2 g/dL છે (સામાન્ય મર્યાદા 13-17).',
        'પ્લેટલેટ કાઉન્ટ એકદમ સ્વસ્થ (2.45 લાખ).',
        'કોઈ બેક્ટેરિયલ ચેપના લક્ષણ નથી.',
        'સલાહ: પૂરતું પાણી પીઓ અને પૌષ્ટિક આહાર લો.'
      ],
      HI: [
        'हीमोग्लोबिन 14.2 g/dL के साथ बिल्कुल सामान्य है।',
        'प्लेटलेट काउंट स्वस्थ सीमा (2.45 लाख) में है।',
        'श्वेत रक्त कणिकाओं में किसी संक्रमण के संकेत नहीं मिले।',
        'सलाह: पर्याप्त पानी पिएं और आयरन युक्त आहार जारी रखें।'
      ],
    },
  },
  {
    id: 'rec-2',
    title: 'OPD Digital Prescription & Vitals',
    gujaratiTitle: 'ઓપીડી ડિજિટલ પ્રિસ્ક્રિપ્શન અને વિગત',
    hindiTitle: 'ओपीडी डिजिटल पर्ची एवं जांच',
    date: '02 Sep 2026',
    hospital: 'Sharda Trust Medical Centre, Ahmedabad',
    doctor: 'Dr. R. Patel (Cardiology)',
    badge: 'Prescription',
    type: 'prescription',
    geminiSummary: {
      EN: [
        'Blood Pressure measured at 122/80 mmHg (Well controlled).',
        'Prescribed Paracetamol 500mg as needed for mild fatigue.',
        'Dietary restriction: Low sodium intake advised.',
        'Follow-up scheduled after 60 days.'
      ],
      GU: [
        'બ્લડ પ્રેશર 122/80 mmHg નોંધાયેલ છે (નિયંત્રણમાં).',
        'હળવા થાક માટે જરૂર પડે ત્યારે પેરાસિટામોલ 500mg.',
        'ખોરાકમાં મીઠાનું પ્રમાણ મધ્યમ રાખવું.',
        '60 દિવસ પછી ફરીથી મુલાકાત.'
      ],
      HI: [
        'रक्तचाप 122/80 mmHg (नियंत्रित) दर्ज किया गया।',
        'हल्के दर्द के लिए आवश्यकतानुसार पैरासिटामोल 500mg।',
        'कम नमक वाला आहार लेने की सलाह दी गई है।',
        '60 दिनों के बाद फॉलो-अप निर्धारित।'
      ],
    },
  },
];

export const PRIMARY_DOCTOR: DoctorProfile = {
  name: 'Dr. A. Sharma',
  qualification: 'MBBS, MD (Medicine) • GMC Reg #48291',
  hospital: 'Civil Hospital Ahmedabad (OPD Wing)',
  experience: '14+ Years Experience',
  rating: 5,
  reviewsCount: 382,
  reviewSnippet: {
    EN: '"Friendly, clear answers"',
    GU: '"ખૂબ મૈત્રીપૂર્ણ અને સ્પષ્ટ સમજાવટ"',
    HI: '"बहुत ही विनम्र और सटीक मार्गदर्शन"',
  },
  reviewerName: 'Kiritbhai V. (Verified Patient)',
  location: 'Ahmedabad (Near Civil Hospital)',
  distance: '0.8 km away • 6 min drive',
  availableTime: 'Today, 10:00 AM - 04:30 PM',
  photoUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
  languages: ['Gujarati', 'Hindi', 'English'],
};

export const DOCTORS_LIST: DoctorProfile[] = [
  PRIMARY_DOCTOR,
  {
    name: 'Dr. Rajesh Patel',
    qualification: 'MD, DM (Cardiology) • GMC Reg #39201',
    hospital: 'Sharda Trust Medical Centre, Ahmedabad',
    experience: '18+ Years Experience',
    rating: 4.9,
    reviewsCount: 512,
    reviewSnippet: {
      EN: '"Thorough heart checkup and calm explanation"',
      GU: '"હૃદયની ખૂબ ઊંડાણપૂર્વક તપાસ અને શાંતિપૂર્ણ સલાહ"',
      HI: '"हृदय रोग की गहन जांच और बहुत ही धैर्यवान सलाह"',
    },
    reviewerName: 'Pravinbhai Shah (Verified Patient)',
    location: 'Ahmedabad (Near Civil Hospital)',
    distance: '1.4 km away • 9 min drive',
    availableTime: 'Today, 02:00 PM - 07:00 PM',
    photoUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80',
    languages: ['Gujarati', 'Hindi', 'English'],
  },
  {
    name: 'Dr. Neha Mehta',
    qualification: 'MBBS, DCH (Pediatrics) • GMC Reg #51902',
    hospital: 'Ahmedabad Child Health Clinic, Shahibaug',
    experience: '10+ Years Experience',
    rating: 5,
    reviewsCount: 290,
    reviewSnippet: {
      EN: '"Excellent with children, gentle care"',
      GU: '"બાળકો સાથે ખૂબ જ લાગણીશીલ અને સચોટ સારવાર"',
      HI: '"बच्चों के लिए बहुत ही संवेदनशील और सटीक इलाज"',
    },
    reviewerName: 'Meenaben Patel (Parent)',
    location: 'Ahmedabad (Shahibaug / Civil Area)',
    distance: '2.1 km away • 12 min drive',
    availableTime: 'Tomorrow, 09:30 AM - 01:00 PM',
    photoUrl: 'https://images.unsplash.com/photo-1594824813581-22668df4f5d2?w=400&auto=format&fit=crop&q=80',
    languages: ['Gujarati', 'Hindi', 'English'],
  }
];

export const TRANSLATIONS = {
  EN: {
    appTitle: 'MEDIX',
    voicePrompt: 'Listening in English...',
    voiceHint: 'Tap microphone to speak symptoms or medicine names',
    medicineHub: 'Medicine Hub',
    scanMedicine: 'SCAN MEDICINE / દવા સ્કેન કરો',
    inventoryTitle: 'Active Medicine Locker',
    verifiedPill: 'Verified Safe',
    expiredWarning: 'Expired Warning',
    healthLocker: 'Health Locker',
    viewRecords: 'VIEW MY RECORDS',
    recordsSubtitle: 'Government ABDM & Hospital Synced',
    digitizedSummary: 'DIGITIZED SUMMARY (Gemini)',
    verifiedDoctors: 'Verified Doctors Nearby',
    locationNear: 'Ahmedabad (Near Civil Hospital)',
    emergency: 'EMERGENCY / કટોકટી',
    sosSub: 'Dial 108 Ambulance / Live GPS',
    home: 'HOME',
    meds: 'MEDS',
    doctors: 'DOCTORS',
    records: 'RECORDS',
    me: 'ME',
    safeDisposalAlert: 'Critical Alert: Do not consume expired medicine. Hand over to civic disposal box.',
    verifiedDoctorBadge: 'GMC & Ayushman Bharat Verified',
    distanceLabel: 'Near Civil Hospital, Asarwa, Ahmedabad',
  },
  GU: {
    appTitle: 'MEDIX',
    voicePrompt: 'ગુજરાતીમાં સાંભળી રહ્યા છીએ...',
    voiceHint: 'દવાનું નામ અથવા લક્ષણો બોલવા માટે માઇક દબાવો',
    medicineHub: 'દવા કેન્દ્ર (Medicine Hub)',
    scanMedicine: 'દવા સ્કેન કરો / SCAN MEDICINE',
    inventoryTitle: 'ચાલુ દવાઓની યાદી',
    verifiedPill: 'માન્ય દવા',
    expiredWarning: 'સમાપ્ત થયેલ દવા',
    healthLocker: 'હેલ્થ લોકર (Health Locker)',
    viewRecords: 'મારા રેકોર્ડ્સ જુઓ (VIEW RECORDS)',
    recordsSubtitle: 'ABDM અને હોસ્પિટલ સાથે જોડાયેલ',
    digitizedSummary: 'ડિજિટાઇઝ્ડ સારાંશ (Gemini AI)',
    verifiedDoctors: 'ચકાસાયેલ તબીબો',
    locationNear: 'અમદાવાદ (સિવિલ હોસ્પિટલ પાસે)',
    emergency: 'કટોકટી / EMERGENCY (108)',
    sosSub: '108 એમ્બ્યુલન્સ / લાઈવ લોકેશન',
    home: 'હોમ',
    meds: 'દવાઓ',
    doctors: 'ડોક્ટર્સ',
    records: 'રેકોર્ડ્સ',
    me: 'પ્રોફાઇલ',
    safeDisposalAlert: 'ચેતવણી: મુદત પૂરી થયેલ દવા વાપરવી હાનિકારક છે. નજીકના ડિસ્પોઝલ બોક્સમાં જમા કરાવો.',
    verifiedDoctorBadge: 'ગુજરાત મેડિકલ કાઉન્સિલ માન્ય',
    distanceLabel: 'સિવિલ હોસ્પિટલ, અસારવા, અમદાવાદ પાસે',
  },
  HI: {
    appTitle: 'MEDIX',
    voicePrompt: 'हिंदी में सुन रहे हैं...',
    voiceHint: 'दवा का नाम या स्वास्थ्य समस्या बोलने के लिए माइक दबाएं',
    medicineHub: 'मेडिसिन हब (Medicine Hub)',
    scanMedicine: 'दवा स्कैन करें / SCAN MEDICINE',
    inventoryTitle: 'सक्रिय दवाओं की सूची',
    verifiedPill: 'प्रमाणित दवा',
    expiredWarning: 'एक्सपायर्ड चेतावनी',
    healthLocker: 'हेल्थ लॉकर (Health Locker)',
    viewRecords: 'मेरे रिकॉर्ड देखें (VIEW RECORDS)',
    recordsSubtitle: 'आयुष्मान भारत (ABDM) सत्यापित',
    digitizedSummary: 'डिजिटाइज्ड सारांश (Gemini AI)',
    verifiedDoctors: 'सत्यापित डॉक्टर',
    locationNear: 'अहमदाबाद (सिविल अस्पताल के पास)',
    emergency: 'आपातकालीन / EMERGENCY',
    sosSub: '108 एम्बुलेंस / तुरंत सहायता',
    home: 'होम',
    meds: 'दवाएं',
    doctors: 'डॉक्टर्स',
    records: 'रिकॉर्ड्स',
    me: 'प्रोफाइल',
    safeDisposalAlert: 'चेतावनी: एक्सपायर हो चुकी दवा का सेवन न करें। सुरक्षित निस्तारण करें।',
    verifiedDoctorBadge: 'राष्ट्रीय चिकित्सा आयोग (NMC) सत्यापित',
    distanceLabel: 'सिविल अस्पताल, असरवा, अहमदाबाद के निकट',
  },
};
